version: "3.8"

services:
  service_postgres:
    image: postgres:14
    container_name: container_postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - volume_postgres:/var/lib/postgresql/data
      # - ./postgres_service/initdb.d:/docker-entrypoint-initdb.d
    user: postgres # rootではなくpostgresユーザーとして実行
    healthcheck: # コンテナの健康状態をチェック
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  volume_postgres:
    name: vpg
